version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./templates:/usr/share/nginx/html
    ports:
      - "5500:80"
